### ISSUE TITLE
Repeated_tasks and logbook parsing

### ISSUE THREAD

**Issue by MorphicResonance** [karlicoss/orgparse#38]
It seems like orgparse get logbook drawer into the body.
If I set property drawer and logbook drawer it wiil get logbook drawer  as body text.

Test this sample.

* DONE header 1 :blog:@flat:template:
CLOSED: [2021-06-02 Wed 00:48]
:PROPERTIES:
:CREATED:  [2021-05-25 Tue 00:33]
:TEMPLATE:  test
:END:
:LOGBOOK:
- State "DONE"       from "SOMEDAY"    [2021-06-02 Wed 00:48]
- State "SOMEDAY"    from "WAITING"    [2021-06-02 Wed 00:48]
- State "WAITING"    from "STARTED"    [2021-06-02 Wed 00:48]
:END:
Fish are aquatic, craniate, gill-bearing animals that lack limbs with digits.
next sentence

** DONE subheader 1 :template:blog:
CLOSED: [2021-05-25 Tue 00:51]
:PROPERTIES:
:CREATED:  [2021-05-25 Tue 00:33]
:TEMPLATE:  test
:END:
:LOGBOOK:
- State "DONE"       from "CANCELLED"  [2021-05-25 Tue 00:51]
- State "CANCELLED"  from              [2021-05-25 Tue 00:51] \\
  stopped
- State "STARTED"    from "WAITING"    [2021-05-25 Tue 00:51]
- State "WAITING"    from "STARTED"    [2021-05-25 Tue 00:37] \\
  time
:END:
The earliest organisms that can be classified as fish were soft-bodied chordates that first appeared during the Cambrian period. 

*** DONE subsubheader :article:
CLOSED: [2021-05-25 Tue 00:51]
:PROPERTIES:
:CREATED:  [2021-05-25 Tue 00:33]
:TEMPLATE:  test
:END:
:LOGBOOK:
- State "DONE"       from "CANCELLED"  [2021-05-25 Tue 00:51]
- State "CANCELLED"  from              [2021-05-25 Tue 00:51] \\
  stopped
:END:
Most fish are ectothermic ("cold-blooded"), allowing their body temperatures to vary as ambient temperatures change, though some of the large active swimmers like white shark and tuna can hold a higher core temperature.

** subheader 2 :blog:
:PROPERTIES:
:CREATED:  [2021-05-25 Tue 00:38]
:END:
Fish are an important resource for humans worldwide, especially as food.

then run node.body .
I breaks on double :end:  and gets logbbok into the body.

**Comment by karlicoss** [comment]
Hey, sorry for late reply. Haven't tried logbook parsing personally, but it's possible! Perhaps somewhat related issue: https://github.com/karlicoss/orgparse/issues/8

A PR with a test that reproduces this will be welcome (even if it's failing at the moment, we can disable it for now and fix it later)

**Comment by MorphicResonance** [comment]
Body can be extracted without drawers. 
By the way, it seems like `repeated_tasks` does not work anymore. I've tried with [example from the docs](repeated_tasks). Something wrong with regex.

**Comment by karlicoss** [comment]
hey, I just checked the doctest from here https://github.com/karlicoss/orgparse/blob/349a61f7ba3f0cbdc753a780179b456b1ecb6038/orgparse/node.py#L1398-L1439 and it does extract repeated tasks for me? Can you post a minimal example which doesn't work for you? Thanks :)

**Comment by MorphicResonance** [comment]
It works.
