### ISSUE TITLE
Support properties in OrgRootNode

### ISSUE THREAD

**Issue by arumugamramaswamy** [karlicoss/orgparse#46]
I would like to extract properties from the OrgRootNode, a use case of this could be to find the ID of an Org Roam Article

**Comment by karlicoss** [comment]
Hi, you refer to this right? https://www.orgroam.com/manual.html#The-Org_002droam-Node-1
I think once this is merged https://github.com/karlicoss/orgparse/pull/42, this would resolve it?

**Comment by arumugamramaswamy** [comment]
> Hi, you refer to this right? https://www.orgroam.com/manual.html#The-Org_002droam-Node-1
> I think once this is merged https://github.com/karlicoss/orgparse/pull/42, this would resolve it? 

Yes! I will close this issue.
