### ISSUE TITLE
QUESTION: Reason about using `codecs.open()`

### ISSUE THREAD

**Issue by buhtz** [karlicoss/orgparse#54]
https://github.com/karlicoss/orgparse/blob/36b31d8151e45ac6701822864816b48446d3dcad/orgparse/__init__.py#L135

I am preparing a little bugfix but stumbled across this line where you use `codecs.open()` instead of `builtin.open()` or `pathlib.Path.open()`.

From your current point of view:

Is there a good and strict reason for this?
Are there any reasons against using the _usual_ `builtin.open()` or `pathlib.Path.open()`?

If there is no need for using `codecs` I will show you in a PR what I have in my mind. ;)

**Comment by karlicoss** [comment]
Hey, seems that it's very very old code, from 2012 https://github.com/karlicoss/orgparse/commit/f8fda1007304ef7f2531b6b566f50bddf572c271

So i'd imagine there is no reason to use it now :) feel free to switch it to `builtin.open`!

**Comment by buhtz** [comment]
Fixed via PR #57
