### ISSUE TITLE
Tags containing letters outside of a-zA-Z

### ISSUE THREAD

**Issue by taxophobia** [karlicoss/orgparse#6]
In file **node.py** the constant **RE_HEADING_TAGS**  should probably be something like `'(.*?)\s*:([\w@:]+):\s*$'` to allow for characters like "ä", "č" and so on in tags that are accepted by org-mode without problems.

Otherwise very helpful little library. Thank you for sharing it!

**Comment by karlicoss** [comment]
@taxophobia thanks! Fixed and added a regression test. Released `0.1.2` on pypi with the fix
