### ISSUE TITLE
Extracting line numbers from org nodes?

### ISSUE THREAD

**Issue by lenianiva** [karlicoss/orgparse#63]
Is it possible to extract the line number from a node? I need this functionality because I want to signal to the user the document is invalid.

**Comment by karlicoss** [comment]
Yep, nodes have a `.linenumber` property, e.g. see usage example here https://github.com/karlicoss/promnesia/blob/78e7d73b40c88c4c0374cd9a495d2347017f4b55/src/promnesia/sources/org.py#L167
