### ISSUE TITLE
Possible mistake in heading regexp

### ISSUE THREAD

**Issue by alphapapa** [karlicoss/orgparse#7]
https://github.com/karlicoss/orgparse/blob/702faa6c05ff0642afc195288999b40f6897723c/orgparse/node.py#L40

Hi,

There may be a mistake in this regexp.  An Org heading requires one or more stars at the beginning of the line, followed by one or more spaces.  But this regexp appears to make the spaces after the stars optional.  This is important, because a star at the beginning of a line, without spaces afterward, may be the beginning of bold text.

**Comment by karlicoss** [comment]
@alphapapa thanks, looks like it shouldn't work indeed, although quick check doesn't reveal the bug :thinking: 
```
[ins] In [1]: import orgparse                                                   

[ins] In [2]: orgparse.loads('*item').children                                  
Out[2]: []

[ins] In [3]: orgparse.loads('*item*').children                                 
Out[3]: []

[ins] In [4]: orgparse.loads('* item').children                                 
Out[4]: [<orgparse.node.OrgNode at 0x7fc02ed247f0>]
```
Presumably some fortunate additional check somewhere. I'll take a closer look tomorrow!

**Comment by alphapapa** [comment]
I was thinking more along the lines of headings without text, which are permitted by Org, e.g.

```org
* Heading with text (A)

The following line is not a heading, because it begins with a 
star but has no spaces afterward, just a newline:

*

** Subheading with text (A1)

This subheading is a child of (A).

The next heading has no text, but it does have a space after
the star, so it's a heading:

* 

This text is under the "anonymous" heading above, which would be (B).

** Subheading with text (B1)

This subheading is a child of the "anonymous" heading (B), not of heading (A).
```

I'm guessing the current code will not parse that outline correctly, but I haven't installed it to test.

**Comment by karlicoss** [comment]
So it actually works fine because of this (it's got space):

https://github.com/karlicoss/orgparse/blob/655bb7648d4e848c9052afc2ee51dad3f2991544/orgparse/node.py#L22

But I fixed the `RE_HEADING_STARS` anyway, less confusion. I added your example as a regression test case too; thanks!
